name: Create releases and publish to npm
on:
  push:
    branches:
      - main
jobs:

  # Run Release Please
  release-please:
    runs-on: ubuntu-latest
    steps:

      # Create a release
      - uses: google-github-actions/release-please-action@v3
        id: release
        with:
          release-type: node
          command: manifest

      # ---------------------------------------------------
      # The rest of the steps here are only run if releases
      # have been created

      - uses: actions/checkout@v4
        if: ${{ steps.release.outputs.releases_created }}

      - uses: actions/setup-node@v4
        with:
          node-version: 18
          cache: 'npm'
          registry-url: 'https://registry.npmjs.org'
        if: ${{ steps.release.outputs.releases_created }}

      - run: npm install
        if: ${{ steps.release.outputs.releases_created }}

      - name: Save release please output
        run: |
          cat << EOF > ./release-please-output.json 
            ${{ toJSON(steps.release.outputs) }}
          EOF
        if: ${{ steps.release.outputs.releases_created }}

      - run: node ./scripts/get-publish-flags.js
        id: publish_flags
        if: ${{ steps.release.outputs.releases_created }}

      - run: npm publish ${{ steps.publish_flags.outputs.workspaces }} --access public
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_AUTH_TOKEN }}
        if: ${{ steps.release.outputs.releases_created }}
